# Generated by Django 4.2.14 on 2024-07-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
        migrations.AddField(
            model_name='product',
            name='puntuation',
            field=models.IntegerField(default=0),
        ),
    ]
