# Generated by Django 4.2.14 on 2024-07-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_product_currency_product_puntuation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'British Pound')], default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainImg',
            field=models.URLField(),
        ),
    ]
