# Generated by Django 4.2.14 on 2024-07-26 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_middle_name_alter_cliente_address_line1_and_more'),
        ('ordenes', '0002_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clientes.cliente'),
        ),
    ]
